### ISSUE TITLE
Consultation

### ISSUE THREAD

**Issue by peshkoff** [mensonen/diameter#12]
Hello! 
I have a question. what's the best way to make a multiapp script?  For example, I need to make some gx calls and some rx calls and both of them need to got replys ... I tried making several SimpleThreadingApplications in one script, but only one works ...

**Comment by mensonen** [comment]
So if I understand you right, you want basically one application to be at the same time Gx and Rx? You send requests through two apps, but want all the responses to land at one single place?

I don't think the stack provides a way to do that outright. My initial thought would have been to have just one application and declare it as a relay (`constants.APP_RELAY` or application ID 4294967295), but that should result in a failed Capabilities-Exchange, unless the other peers you're connecting with are relay agents too. Might be worth trying though. 

An alternative approach would be to just have two applications, but build them from scratch using the base `Application` or `ThreadingApplication` and have both of them send the answers to somewhere else in your codebase.

**Comment by peshkoff** [comment]
No, 1 node and 2 application. I think it is working solution? I'm sending all packets to 1 peer (dra)

**Comment by mensonen** [comment]
Just having two different applications in the same node, both using the same peer, is definitely is a working configuration. As long as you pass two *separate* instances of applications to the node, those two applications will receive their answers also separately.

I.e. something like:

```python
peer_cfg = node.add_peer(...)

client1 = SimpleThreadingApplication(
    application_id=APP_3GPP_SY,
    is_auth_application=True, is_acct_application=True)
node.add_application(client1, [peer_cfg])

client2 = SimpleThreadingApplication(
    application_id=APP_3GPP_GX,
    is_auth_application=True, is_acct_application=True)
node.add_application(client2, [peer_cfg])
```

When I test it like above, a request I send through `client1` gets its answer also routed to `client1`. A request sent through `client2` has its answer routed to `client2`.

**Comment by peshkoff** [comment]
Yes, it's working configuration! Thanks 
I have another question =) How can I correctly create AVP_FRAMED_IPV6_PREFIX?

```
            framed_ipv6 = '2a00:1fa2:c863:8c7e::'
            framed_ipv6_prefix = Avp.new(AVP_FRAMED_IPV6_PREFIX)
            framed_ipv6_prefix.value = socket.inet_pton(socket.AF_INET6, framed_ipv6)
            print(framed_ipv6_prefix)
            
            avp_bytes = bytes.fromhex("000000614000001200402a001fa2c8638c7e0000")
            framed_ipv6_prefix = Avp.from_bytes(avp_bytes)
            print(framed_ipv6_prefix)   
```
And output (second is correct)
Framed-IPv6-Prefix <Code: 0x61, Flags: 0x40 (-M-), Length: 24, Val: b'*\x00\x1f\xa2\xc8c\x8c~\x00\x00\x00\x00\x00\x00\x00\x00'>
Framed-IPv6-Prefix <Code: 0x61, Flags: 0x40 (-M-), Length: 18, Val: b'\x00@*\x00\x1f\xa2\xc8c\x8c~'>

![image](https://github.com/mensonen/diameter/assets/8603965/09318061-d06f-4732-be10-10b17caf16da)

**Comment by mensonen** [comment]
The [specification for Framed-IPv6-Prefix](https://datatracker.ietf.org/doc/html/rfc3162#autoid-6) states that the value contains of a reserved value (always zero), a prefix length *in bits*, followed by the actual prefix value. So in your case it's `0x00` + `0x40` + `0x2a001fa2c8638c7e`. 

You can construct this manually, for instance with:
```pycon
>>> framed_ipv6 = bytes.fromhex("2a001fa2c8638c7e")
>>> framed_ipv6_prefix = Avp.new(AVP_FRAMED_IPV6_PREFIX)
>>> framed_ipv6_prefix.value = b"\00" + (len(framed_ipv6) * 8).to_bytes() + framed_ipv6
>>> print(framed_ipv6_prefix)
Framed-IPv6-Prefix <Code: 0x61, Flags: 0x40 (-M-), Length: 18, Val: b'\x00@*\x00\x1f\xa2\xc8c\x8c~'>
```

You can also do it with socket.inet_pton or even the native ipaddress module, but these produce the prefix always in expanded format, so your length will not be 0x40 like in your example. It's still a valid AVP and a valid IPv6 prefix, and spec permits these, but it won't be identical to your screenshot. A way with inet_pton would be:

```pycon
>>> import socket
>>> framed_ipv6 = socket.inet_pton(socket.AF_INET6, "2a00:1fa2:c863:8c7e::")
>>> framed_ipv6_prefix = Avp.new(AVP_FRAMED_IPV6_PREFIX)
>>> framed_ipv6_prefix.value = b"\00" + (len(framed_ipv6) * 8).to_bytes() + framed_ipv6
>>> print(framed_ipv6_prefix)
Framed-IPv6-Prefix <Code: 0x61, Flags: 0x40 (-M-), Length: 26, Val: b'\x00\x80*\x00\x1f\xa2\xc8c\x8c~\x00\x00\x00\x00\x00\x00\x00\x00'>
```
