### ISSUE TITLE
Exception in _flag_connection_as_ready

### ISSUE THREAD

**Issue by Riccardo-78** [mensonen/diameter#13]
```
<PeerConnection(faf40a94a9ea, 10.0.x.x> failed to handle message: 'str' object has no attribute 'is_ready'
Traceback (most recent call last):
  File "/opt/sre/lib/python3.11/site-packages/diameter/node/node.py", line 850, in _receive_message
    self.receive_cea(conn, msg)
  File "/opt/sre/lib/python3.11/site-packages/diameter/node/node.py", line 1243, in receive_cea
    self._flag_connection_as_ready(conn)
  File "/opt/sre/lib/python3.11/site-packages/diameter/node/node.py", line 579, in _flag_connection_as_ready
    app.is_ready.set()
    ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_ready'
```

If I understand correctly `self._peer_routes` is declared as `dict[str, dict[Application | str, list[Peer]]] ` so app can be a string (with content "_default"). What's the best thing to do here, skip the setting of the is_ready event?

**Comment by mensonen** [comment]
This looks like a bug. The `_flag_connection_as_ready` helper should skip apps that are not actual apps. The "_default" dictionary entry exists just for routing purposes, so there is no actual app to flag as ready to receive connections. The entry is already ignored elsewhere, just not in this method.

I'll add a fix for this and push out a release.

In the meantime, do you actually need the `is_default` property for a peer? 

If you flag a peer as default, it results in every request being routed through it and your other peers are permanently ignored. Unless you really want to address only one peer constantly, you're probably better off not setting it at all and leaving the node to load balance between the peers.

**Comment by Riccardo-78** [comment]
Thanks @mensonen , you are right this bug can be triggered only if `is_default` is set, I'll follow your suggestion.
