### ISSUE TITLE
Add served realms without peers

### ISSUE THREAD

**Issue by BungaaFACE** [mensonen/diameter#15]
Hello, please make a function for node to add served realms, that is not used in peers. 

For now i got workaround function:
```
class chNode(Node):
    def add_realm(self, realm_name, app_id):
        '''Add realm to served realm list'''
        for app_peer in list(self._peer_routes.keys()):
            for app, peers in self._peer_routes[app_peer].items():
                if not isinstance(app, Application):
                    continue
                if app.application_id == app_id:
                    self._peer_routes[realm_name] = {}
                    self._peer_routes[realm_name][app] = peers
                    break
```
Need to add support if realm already added to not break exist realm

**Comment by mensonen** [comment]
Can you outline a bit what your actual use case for this is? What is the actual, real-world scenario where this happens?

Since version 0.7.1, multiple realms are anyway supported. In the current version, you can do something like this:

```python
node = Node("servername", "server-realm")
peer_cfg_1 = node.add_peer("aaa://client1.realm1:6092", "realm1")
peer_cfg_2 = node.add_peer("aaa://client2.realm2:6093", "realm2")
node.start()

cc_app = Server(application_id=APP_DIAMETER_CREDIT_CONTROL_APPLICATION, is_auth_application=True)
node.add_application(cc_app, [peer_cfg_1, peer_cfg_2])
```

The snippet above would configure the `cc_app` to accept messages from "realm1" and "realm2", while routing responses back correctly using the proper realm names. Is this perhaps what you're after?

**Comment by BungaaFACE** [comment]
When DSR recieves message with specific parameter he copies this message to our python application.

Example:
Origin realm isn't dsr01.fqdn.com (dsr-peer) but origin-1.fqdn.com or origin-2.fqdn.com etc. So in order to recieve this message and dont get answer from python "REALM NOT SERVED" i need to add realms "origin-1.fqdn.com" and "origin-2.fqdn.com" to served realms for this dsr.

As for now i'm adding manually this realms to Node._peer_routes to accept messages.

**Comment by mensonen** [comment]
I think I need a bit more information before I can build a test scenario that I can test against.

Do I understand correctly that you:

* Configure one `Node` which connects with _one_  `Peer` and routes to _one_ instance of `Application`
* From that one peer, the node receives sometimes messages with different realm names
* Regardless of which origin realm the message has, the node should not reject it and should always route to that same application

**Comment by BungaaFACE** [comment]
`Configure one Node which connects with one Peer and routes to one instance of Application`
- one or more peers

`From that one peer, the node receives sometimes messages with different realm names`
- right

`Regardless of which origin realm the message has, the node should not reject it and should always route to that same application`
- right

Realms can be configured during Peer creation (for single peer) or as the Node function (for all Node peers).
This feature is not necessary, but I will be glad if you add it

**Comment by mensonen** [comment]
Okay, to me that scenario looks like something that would be best suited to be as part of `add_application`. Something like

```python
peer = node.add_peer("aaa://clientname:6092", "clientrealm")
node.add_application(app, [peer], ["list", "of additional", "realms"])
```

As `add_application` is the method that actually maintains the `_peer_routes` internal routing table, this would be the most convenient place to implement this. It would also cover scenarios where peers are added dynamically much later than the initial node configuration is done (e.g. through auto-discovery), and where multiple apps would re-use the same peers.

**Comment by BungaaFACE** [comment]
Thats good decision, looks great

**Comment by mensonen** [comment]
I've added this in d99ae6f. Do you want to test the attached dev build and see if it covers your use scenario as expected?

[python_diameter-0.7.3.dev4+gd99ae6f.zip](https://github.com/user-attachments/files/16509990/python_diameter-0.7.3.dev4%2Bgd99ae6f.zip)

Alternatively, as the change is really just 4 lines, you could copy them into your forked copy and let me know if it's what you were after.

**Comment by BungaaFACE** [comment]
Tested out on local server and client, looks like it's working. Thank you! 

When to expect the new version release?

**Comment by mensonen** [comment]
v0.7.3 just released and contains this feature.

**Comment by BungaaFACE** [comment]
Thank you for your help. Tomorrow or Friday i will try to update to the latest version and keep an eye on it for some time.
