### ISSUE TITLE
Question: credit-control 

### ISSUE THREAD

**Issue by BungaaFACE** [mensonen/diameter#17]
Can you help me with one question?

In mscc class i have two report reasons (one is mscc.report_reason and another in mscc.used_service_unit[0].reporting_reason)

```
MultipleServicesCreditControl(...,
                              used_service_unit=[UsedServiceUnit(...
                                                                 reporting_reason=None,
                                                                 ...)],
                              ...
                              reporting_reason=[7],
                              ...)
```

So far i saw Forced reauth and QHT reasons in mscc.report_reason but never saw any report reason in used service units. Can you clarify this for me?

**Comment by mensonen** [comment]
The additional location for the Reporting-Reason AVP within the Used-Service-Unit is valid. It's a 3GPP extension defined in [ETSI 132.299](https://www.etsi.org/deliver/etsi_ts/132200_132299/132299/15.03.00_60/ts_132299v150300p.pdf).  When a reporting reason is given within an individual Used-Service-Unit AVP, the reason applies to that single quota only.

The spec writes:

> The values QHT, FINAL, VALIDITY_TIME, FORCED_REAUTHORISATION, RATING_CONDITION_CHANGE,
UNUSED_QUOTA_TIMER apply for all quota types and are used directly in the Multiple-Services-Credit-Control
AVP, whereas the values THRESHOLD, QUOTA_EXHAUSTED and OTHER_QUOTA_TYPE apply to one
particular quota type and shall occur only in the Used-Service-Units AVP.

So it would match with what you're seeing; `QHT` and `FORCED_REAUTHORISATION` appear only directly under MSCC. If you're not seeing the other reporting reasons within the used service unit AVPs then it probably means that the vendor implementation or setup you're talking to doesn't use it for anything. 

It *is* a commonly used scenario though. Here's a sample from live traffic that includes both Reporting-Reasons at the same time:

![Screenshot_20240903_202729](https://github.com/user-attachments/assets/fa8bd881-388a-47a2-8545-240b9ec1a25b)

My approach would be that if you are expecting the `THRESHOLD`, `QUOTA_EXHAUSTED` and `OTHER_QUOTA_TYPE` reporting reasons, then you should look for them under Used-Service-Unit only. If you do not care about those conditions, you can ignore reporting reason under Used-Service-Unit.

**Comment by BungaaFACE** [comment]
Thank you for your explanation, its clear for me now
